#!/usr/bin/env bash

set -o errexit

export ROOT_PATH="$(realpath $(dirname $BASH_SOURCE))"
export BIN_PATH="$ROOT_PATH/bin"
export SRC_PATH="$ROOT_PATH/src"
export NOTEBOOK="$1"

if [ -x "$(command -v "zellij")" ]; then
	export ZEL="$(which zellij)"
else
	export ZEL="$BIN_PATH/zellij" # $ZELLIJ is taken over by Zellij
fi

if [ -x "$(command -v "gum")" ]; then
	export GUM="$(which gum)"
else
	export GUM="$BIN_PATH/gum"
fi

for script in $SRC_PATH/*.sh; do
	source $script
done

if [ "$1" = "--help" ]; then
	print_help
	exit
fi

bootstrap "$ROOT_PATH/bin"

if ! is_script_sourced; then
	while [[ "$#" -gt 0 ]]; do
		case $1 in
		# -t|--theme) export OPT_THEME="$2"; shift ;;
		--no-confirm) export OPT_NO_CONFIRM="true" ;;
		--no-warn) export OPT_NO_WARN="true" ;;
		-*)
			print_error_argument "$1"
			exit 1
			;;
		*) export NOTEBOOK="$1" ;;
		esac

		shift
	done

	if [ -z "$NOTEBOOK" ] || [ "${NOTEBOOK:0:1}" = "-" ]; then
		# show docs if no notebook is passed
		export NOTEBOOK="$ROOT_PATH/docs/01-intro.md"
		export NOTEBOOKS="$ROOT_PATH/docs"
	else
		export NOTEBOOK="$(realpath $NOTEBOOK)"

		if [ -f "$NOTEBOOK" ]; then
			export NOTEBOOKS="$(dirname $NOTEBOOK)"
		elif [ -d "$NOTEBOOK" ]; then
			export NOTEBOOKS="$NOTEBOOK"
		fi
	fi

	$ZEL --layout "$SRC_PATH/zellij/layout.kdl"
	tput cuu 1
fi
